### PR TITLE
add Wood EOH base

### PR DESCRIPTION
**Pull request by Nxer**

### CODE REVIEW

**Comment by AimaGod** [comment]
Suggestion about EOW: Wouldn't it be good if each voltage tier increases by 50% (not multiplicative) final products? Like at LV it gives 100 iron dust and each tier it increases by 50%, or maybe it can speed up by 50% the time of processing. I'm sorry that I can't help that much but I'm not a programmer and Idk how it works doing codes

**Comment by AimaGod** [comment]
Oh right, about when it fails, wouldn't it be fine if it gives back steam or lava?

**Comment by Nxer** [comment]
> Oh right, about when it fails, wouldn't it be fine if it gives back steam or lava?

Now it doesn't work. I have not written it processing logic.

**Comment by Nxer** [comment]
> Oh right, about when it fails, wouldn't it be fine if it gives back steam or lava?

Oh I got. It can be a steam generator like EOH output spacetime when fails.

**Comment by AimaGod** [comment]
Yeah, u can make it work with water and energy (depending on energy tier it goes faster or can produce more resources) and when it fails it gives just steam instead of nothing, but if it success it gives resources and a % of energy back

**Pull request merged**
