### PR TITLE
Endgame goal

### PR DESCRIPTION
**Pull request by evgengoldwar**
### Twist Token
image

image

### Liquid Stargate
image

### Stabilise Void Matter
image

### UXV
image

### UMV
image

### UIV
image

### UEV
image

### UHV
image

### UV
image

### ZPM
image

### LUV
image

### IV
image

### EV
image

### HV
image

### MV
image

### LV
image

### CODE REVIEW

**Comment by horobo** [comment]
I think it can be worse

**Comment by Reflex18** [comment]
All i have to say is that cat better be animated.

**Comment by evgengoldwar** [comment]
> All i have to say is that cat better be animated.

Asked the who did it to improve the quality.

**Comment by evgengoldwar** [comment]
> All i have to say is that cat better be animated.

Update texture

**Review by Nxer — APPROVED** [review]

**Pull request merged**
